# Generated by Django 5.1 on 2024-12-21 19:59

import django.core.validators
import p2p_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='DOB',
            field=models.DateField(blank=True, help_text='You must be at least 18 years old to register as a seller', null=True, validators=[p2p_site.models.validate_age]),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='delivery_radius',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='product_categories',
            field=models.ManyToManyField(related_name='seller', to='p2p_site.productcategory'),
        ),
    ]
