# Generated by Django 5.1 on 2024-12-22 15:51

import p2p_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0002_productcategory_customuser_is_seller_seller_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product_categories',
        ),
        migrations.AlterField(
            model_name='seller',
            name='id_card',
            field=models.ImageField(upload_to=p2p_site.models.seller_directory_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_photo',
            field=models.ImageField(upload_to=p2p_site.models.seller_directory_path),
        ),
    ]
