# Generated by Django 5.1 on 2025-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0002_remove_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='p2p_site.product'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
