# Generated by Django 5.1 on 2025-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0003_userprofile_favourites_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carts',
            field=models.ManyToManyField(blank=True, related_name='added_to_cart_by', to='p2p_site.product'),
        ),
    ]
