# Generated by Django 5.1 on 2024-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0004_order_orderupdate_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
