# Generated by Django 5.1 on 2024-12-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_site', '0007_alter_chat_options_chat_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('purchase', 'Purchase Discussion'), ('offer', 'Offer Discussion')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='p2p_site.product'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seller',
        ),
    ]
