export const SELLER_REGISTER_REQUEST = 'SELLER_REGISTER_REQUEST';
export const SELLER_REGISTER_SUCCESS = 'SELLER_REGISTER_SUCCESS';
export const SELLER_REGISTER_FAIL = 'SELLER_REGISTER_FAIL';

export const SELLER_PROFILE_REQUEST = 'SELLER_PROFILE_REQUEST';
export const SELLER_PROFILE_SUCCESS = 'SELLER_PROFILE_SUCCESS';
export const SELLER_PROFILE_FAIL = 'SELLER_PROFILE_FAIL';